//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VatServiceReference
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ec.europa.eu:taxud:tedb:services:v1:IVatRetrievalService:types")]
    public partial class errorType
    {
        
        private string codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ec.europa.eu:taxud:tedb:services:v1:IVatRetrievalService:types")]
    public partial class categoryType
    {
        
        private string identifierField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string identifier
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ec.europa.eu:taxud:tedb:services:v1:IVatRetrievalService:types")]
    public partial class responseCodeDetailsType
    {
        
        private string valueField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ec.europa.eu:taxud:tedb:services:v1:IVatRetrievalService:types")]
    public partial class rateValueType
    {
        
        private rateValueTypeEnum typeField;
        
        private double valueField;
        
        private bool valueFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public rateValueTypeEnum type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueSpecified
        {
            get
            {
                return this.valueFieldSpecified;
            }
            set
            {
                this.valueFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ec.europa.eu:taxud:tedb:services:v1:IVatRetrievalService:types")]
    public enum rateValueTypeEnum
    {
        
        /// <remarks/>
        DEFAULT,
        
        /// <remarks/>
        NOT_APPLICABLE,
        
        /// <remarks/>
        OUT_OF_SCOPE,
        
        /// <remarks/>
        EXEMPTED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ec.europa.eu:taxud:tedb:services:v1:IVatRetrievalService:types")]
    public partial class retrieveVatRatesReqType
    {
        
        private string[] memberStatesField;
        
        private System.DateTime situationOnField;
        
        private string[] categoriesField;
        
        private string[] cnCodesField;
        
        private string[] cpaCodesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("isoCode", DataType="token", IsNullable=false)]
        public string[] memberStates
        {
            get
            {
                return this.memberStatesField;
            }
            set
            {
                this.memberStatesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime situationOn
        {
            get
            {
                return this.situationOnField;
            }
            set
            {
                this.situationOnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("identifier", IsNullable=false)]
        public string[] categories
        {
            get
            {
                return this.categoriesField;
            }
            set
            {
                this.categoriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("value", IsNullable=false)]
        public string[] cnCodes
        {
            get
            {
                return this.cnCodesField;
            }
            set
            {
                this.cnCodesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("value", IsNullable=false)]
        public string[] cpaCodes
        {
            get
            {
                return this.cpaCodesField;
            }
            set
            {
                this.cpaCodesField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:ec.europa.eu:taxud:tedb:services:v1:VatRetrievalService", ConfigurationName="VatServiceReference.vatRetrievalService")]
    public interface vatRetrievalService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ec.europa.eu:taxud:tedb:services:v1:VatRetrievalService/RetrieveVatRates", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(VatServiceReference.errorType[]), Action="urn:ec.europa.eu:taxud:tedb:services:v1:VatRetrievalService/RetrieveVatRates", Name="retrieveVatRatesFaultMsg", Namespace="urn:ec.europa.eu:taxud:tedb:services:v1:IVatRetrievalService")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VatServiceReference.retrieveVatRatesResponse> retrieveVatRatesAsync(VatServiceReference.retrieveVatRatesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ec.europa.eu:taxud:tedb:services:v1:IVatRetrievalService:types")]
    public partial class retrieveVatRatesRespTypeVatRateResults
    {
        
        private string memberStateField;
        
        private rateTypeEnum typeField;
        
        private rateValueType rateField;
        
        private responseCodeDetailsType[] cnCodesField;
        
        private responseCodeDetailsType[] cpaCodesField;
        
        private categoryType categoryField;
        
        private string commentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=0)]
        public string memberState
        {
            get
            {
                return this.memberStateField;
            }
            set
            {
                this.memberStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public rateTypeEnum type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public rateValueType rate
        {
            get
            {
                return this.rateField;
            }
            set
            {
                this.rateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("code", IsNullable=false)]
        public responseCodeDetailsType[] cnCodes
        {
            get
            {
                return this.cnCodesField;
            }
            set
            {
                this.cnCodesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("code", IsNullable=false)]
        public responseCodeDetailsType[] cpaCodes
        {
            get
            {
                return this.cpaCodesField;
            }
            set
            {
                this.cpaCodesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public categoryType category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ec.europa.eu:taxud:tedb:services:v1:IVatRetrievalService:types")]
    public enum rateTypeEnum
    {
        
        /// <remarks/>
        STANDARD,
        
        /// <remarks/>
        REDUCED,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class retrieveVatRatesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ec.europa.eu:taxud:tedb:services:v1:IVatRetrievalService", Order=0)]
        public VatServiceReference.retrieveVatRatesReqType retrieveVatRatesReqMsg;
        
        public retrieveVatRatesRequest()
        {
        }
        
        public retrieveVatRatesRequest(VatServiceReference.retrieveVatRatesReqType retrieveVatRatesReqMsg)
        {
            this.retrieveVatRatesReqMsg = retrieveVatRatesReqMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class retrieveVatRatesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:ec.europa.eu:taxud:tedb:services:v1:IVatRetrievalService", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("vatRateResults", Namespace="urn:ec.europa.eu:taxud:tedb:services:v1:IVatRetrievalService:types", IsNullable=false)]
        public VatServiceReference.retrieveVatRatesRespTypeVatRateResults[] retrieveVatRatesRespMsg;
        
        public retrieveVatRatesResponse()
        {
        }
        
        public retrieveVatRatesResponse(VatServiceReference.retrieveVatRatesRespTypeVatRateResults[] retrieveVatRatesRespMsg)
        {
            this.retrieveVatRatesRespMsg = retrieveVatRatesRespMsg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface vatRetrievalServiceChannel : VatServiceReference.vatRetrievalService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class vatRetrievalServiceClient : System.ServiceModel.ClientBase<VatServiceReference.vatRetrievalService>, VatServiceReference.vatRetrievalService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public vatRetrievalServiceClient() : 
                base(vatRetrievalServiceClient.GetDefaultBinding(), vatRetrievalServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.vatRetrievalService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public vatRetrievalServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(vatRetrievalServiceClient.GetBindingForEndpoint(endpointConfiguration), vatRetrievalServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public vatRetrievalServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(vatRetrievalServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public vatRetrievalServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(vatRetrievalServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public vatRetrievalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VatServiceReference.retrieveVatRatesResponse> VatServiceReference.vatRetrievalService.retrieveVatRatesAsync(VatServiceReference.retrieveVatRatesRequest request)
        {
            return base.Channel.retrieveVatRatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<VatServiceReference.retrieveVatRatesResponse> retrieveVatRatesAsync(VatServiceReference.retrieveVatRatesReqType retrieveVatRatesReqMsg)
        {
            VatServiceReference.retrieveVatRatesRequest inValue = new VatServiceReference.retrieveVatRatesRequest();
            inValue.retrieveVatRatesReqMsg = retrieveVatRatesReqMsg;
            return ((VatServiceReference.vatRetrievalService)(this)).retrieveVatRatesAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.vatRetrievalService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.vatRetrievalService))
            {
                return new System.ServiceModel.EndpointAddress("http://ec.europa.eu/taxation_customs/tedb/ws/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return vatRetrievalServiceClient.GetBindingForEndpoint(EndpointConfiguration.vatRetrievalService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return vatRetrievalServiceClient.GetEndpointAddress(EndpointConfiguration.vatRetrievalService);
        }
        
        public enum EndpointConfiguration
        {
            
            vatRetrievalService,
        }
    }
}
